

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Crypto 1131301",
    "author": "NeuralNetwork123334",
    "url": "http://www.cryptoinvest.ee/",
    "likes": 10
}