

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Daily life in data science",
    "author": "NeuralNetwork123",
    "url": "http://www.variance.ee/",
    "likes": 10
}